language: java

jdk:
  - oraclejdk8

sudo:
  false

cache:
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper

install:
  ./gradlew assemble

script:
  ./gradlew clean check --info

after_script:
  ./gradlew -Pversioneye.api_key=$VERSIONEYE_API_KEY versioneye-update